# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name:          First User
  admin_email:         user@example.com
  admin_password:      changeme
  secret_key_base:     8af63b7aa9452e1580eceab588b26bbfc22a368665133e5fed719b1c4587ce7131b462667ca9cf0ed52bdc53bd23981bab69c5181b0e5c1306259e3b434d7485
  mandrill_username:   app26446958@heroku.com
  mandrill_apikey:     kOTl7XLZtAGag1IUdTNoTQ
  twilio_sid:          "AC4dca77033ee4b1d1ec92255ef13486ce"
  twilio_token:        "43bf1a9837200ccc09ad342ae2695931"
  twilio_phone_number: "6475601631"

test:
  secret_key_base: d07d2608619c76ca5911834c1639c3ca4448694082c1e4b582a4971ef9773ed00f49827890eccc24fddf06ff5f68e32b798ed431ebd0e546904b49199ea7d87a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  mandrill_username: <%= ENV["MANDRILL_USERNAME"] %>
  mandrill_apikey: <%= ENV["MANDRILL_APIKEY"] %>
  twilio_sid: <%= ENV["TWILIO_SID"] %>
  twilio_token: <%= ENV["TWILIO_TOKEN"] %>
  twilio_phone_number: <%= ENV["TWILIO_PHONE_NUMBER"] %>
